
module.exports = {
    UNKNOWN_NUMBER: 0,
    INTERNATIONAL_NUMBER: 1,
    NATIONAL_NUMBER: 2,
    NETWORK_SPECIFIC_NUMBER: 3,
    SUBSCRIBER_NUMBER: 4,
    ALPHANUMERIC_NUMBER: 5,
    ABBREVIATED_NUMBER: 6,

    UNKNOWN_NUMBERING_PLAN: 0,
    ISDN_NUMBERING_PLAN: 1,
    DATA_NUMBERING_PLAN: 2,
    TELEX_NUMBERING_PLAN: 4,
    NATIONAL_NUMBERING_PLAN: 8,
    PRIVATE_NUMBERING_PLAN: 9,
    ERMES_NUMBERING_PLAN: 10,

    SMS_DELIVER: 0,
    SMS_STATUS_REPORT: 2,
    SMS_SUBMIT_REPORT: 1,

    SMS_DELIVER_REPORT: 0,
    SMS_COMMAND: 2,
    SMS_SUBMIT: 1,

    ALPHABET_7BIT: "@£$¥èéùìòÇ\nØø\rÅåΔ_ΦΓΛΩΠΨΣΘΞ\x1bÆæßÉ !\"#¤%&'()*+,-./0123456789:;<=>?¡ABCDEFGHIJKLMNOPQRSTUVWXYZÄÖÑÜ§¿abcdefghijklmnopqrstuvwxyzäöñüà",

    NO_VALIDITY_PERIOD: 0,
    RELATIVE_VALIDITY_PERIOD: 2,
    ENHANCED_VALIDITY_PERIOD: 1,
    ABSOLUTE_VALIDITY_PERIOD: 3
};